[server]
# Server configuration settings

[database]
# Database connection and configuration settings

[integration]
# Integration settings with external services

[tasks]
# Task scheduling and management configuration

[logging]
# Logging configuration settings
level = "info"
file = "/home/clara-sorrenti/Documents/MF_MCP/logs/mcp-warp.log"
format = "json"

[logging.rotation]
max_size = "100MB"
max_files = 5
compress = true

[metrics]
# Metrics collection and reporting settings
enabled = true
endpoint = "/metrics"
port = 9090

[security]
# Security and authentication settings
tls_enabled = false
auth_required = true
allowed_origins = ["http://localhost:*"]

[security.rate_limit]
requests_per_second = 10
burst = 20
