[server]
# Server configuration settings
host = "localhost"
port = 8080

[database]
# Database connection and configuration settings
redis_url = "redis://localhost:6379"
redis_pool_size = 10

[redis]
host = "localhost"
port = 6379
db = 0
pool_size = 10

[redis.search]
index_prefix = "knowledge:"
default_language = "english"
default_score_field = "_score"
fuzzy_distance = 2
max_expansions = 50

[integration]
# Integration settings with external services

[tasks]
# Task scheduling and management configuration

[logging]
# Logging configuration settings
level = "info"
file = "/home/clara-sorrenti/Documents/MF_MCP/logs/mcp-warp.log"
format = "json"

[logging.rotation]
max_size = "100MB"
max_files = 5
compress = true

[metrics]
# Metrics collection and reporting settings
enabled = true
endpoint = "/metrics"
port = 9090

[security]
# Security and authentication settings
tls_enabled = false
auth_required = true
allowed_origins = ["http://localhost:*"]

[security.rate_limit]
requests_per_second = 10
burst = 20
