[server]
host = "127.0.0.1"
port = 8080
environment = "development"
version = "0.1.0"

[environment]
trello_key = "${TRELLO_KEY}"
trello_token = "${TRELLO_TOKEN}"
trello_board_id = "${TRELLO_BOARD_ID}"
redis_url = "${REDIS_URL}"
rust_log = "${RUST_LOG}"
heartbeat_timeout = "${HEARTBEAT_TIMEOUT}"
