pub mod database;
pub mod heartbeat;
pub mod memory;
pub mod tasks;
pub mod trello;
pub mod utils;
pub mod vector_store;
pub mod schemas;
use std::env;
use std::time::Duration;
use crate::utils::RedisManager;
use crate::utils::get_heartbeat_timeout;
use crate::utils::get_trello_config;
use crate::schemas::{AgentStatus, TrelloCard};
use serde_json::Value;
use anyhow::Result;
use reqwest::Client;   
use redis::AsyncCommands;
use redis::JsonAsyncCommands;
use serde_json::json;
use uuid::Uuid;
use flate2::write::ZlibEncoder;
use flate2::Compression;
use std::io::Write;
